title: Cygnus Trio
description: London-based piano trio formed in 2012
theme: null


exclude:
 - Gemfile
 - Gemfile.lock


# This caused links to break. They need to be fixed before setting

